---
title: "R Notebook"
output: html_notebook
---

```{r Packages}
library(ggplot2)
library(Rsolnp)
library(dplyr)
library(plotrix)
```


##### MODELS #####


```{r Model 1: No JND Model}
# parameters
w.start <- 1/3
w.min <- 0
w.max <- 3
g.start <- 1/3
g.min <- 0
g.max <- 3

# probability function
# calculates the probability that the subject will respond correctly on a given ratio (r) based on the current guesses for w and g
prob.NoJND <- function(w,g,r){
  p<-pnorm((r-1)/(w*sqrt(1+r^2)))
  prob <- (1-g)*p+(g/2)
  return(prob)
}

# negative log likelihood
NLL.NoJND <- function(subjectParams, trialParams,outcomes) {
  p <- prob.NoJND(subjectParams[1],subjectParams[2],trialParams)
  probofobs <- log(p)*outcomes + log(1-p)*(1-outcomes)
  negativeloglikelihood <- -sum(probofobs)
  return(negativeloglikelihood)
}

# lower and upper bounds
numParam.NoJND <- 2
lb.NoJND <- c(w.min,g.min)
ub.NoJND <- c(w.max,g.max)

# initial guesses
subjectParams.NoJND <- c(w.start,g.start) 
```

```{r Model 2: Intuitive JND Model}
# parameters
w.start <- 1/3
w.min <- 0
w.max <- 3
g.start <- 1/3
g.min <- 0
g.max <- 3
jnd.start <- 0.05
jnd.min <- 0
jnd.max <- 3

# probability function 
prob.IntJND <- function(w,g,jnd,r){
  p<-ifelse( r>(1+jnd), pnorm(((r-jnd)-1)/(w*sqrt(1+(r-jnd)^2))), .5 )
  prob <- (1-g)*p+(g/2)
  return(prob)
}

# objective function
NLL.IntJND <- function(subjectParams, trialParams,outcomes) {
  p <- prob.IntJND(subjectParams[1],subjectParams[2],subjectParams[3], trialParams)
  probofobs <- log(p)*outcomes + log(1-p)*(1-outcomes)
  negativeloglikelihood <- -sum(probofobs)
  return(negativeloglikelihood)
}

# lower and upper bounds
numParam.IntJND <- 3
lb.IntJND <- c(w.min,g.min,jnd.min)
ub.IntJND <- c(w.max,g.max,jnd.max)
subjectParams.IntJND <- c(w.start,g.start,jnd.start) # initial guesses
```

```{r Model 3: Common JND Model}
# parameters
alpha.start <- 1.05
alpha.min <- 0
alpha.max <- 3
beta.start <- 12
beta.min <- 0
beta.max <- 40

# probability function
prob.ComJND <- function(alpha, beta, g, r){ 
  prob <- 1-.5*(exp(-(r/alpha)^beta)) 
  probGuess <- (1-g)*prob+(g/2)
  return (probGuess)
}

# negative log likelihood
NLL.ComJND <- function(subjectParams, trialParams,outcomes) {
  p <- prob.ComJND(subjectParams[1],subjectParams[2], subjectParams[3], trialParams)
  probofobs <- log(p)*outcomes + log(1-p)*(1-outcomes)
  negativeloglikelihood <- -sum(probofobs)
  return(negativeloglikelihood)
}

# lower and upper bounds
numParam.ComJND <- 3
lb.ComJND <- c(alpha.min, beta.min,  g.min) 
ub.ComJND <- c(alpha.max, beta.max, g.max) 

# initial guesses
subjectParams.ComJND <- c(alpha.start, beta.start, g.start) 
```

```{r Example plots}
# generate example data
# set parameter values
testAlpha <- 1.25
testBeta <- 14
testW <- .125
testG <- 0.2
testJND <- .05

exampleDat <- data.frame()
for (ratio in seq(1,1.5,.01)){
  pNoJND <- prob.NoJND(testW, testG, ratio)
  pIntJND <- prob.IntJND(testW, testG, testJND, ratio)
  pComJND <- prob.ComJND(testAlpha, testBeta, testG, ratio)
  exampleDat <- rbind(exampleDat, data.frame(ratio, pNoJND, pIntJND, pComJND))
}

# Plots

# No JND model
ggplot(exampleDat, aes(x = ratio, y = pNoJND))+
  theme_classic(base_size=15)+
  ylab("Performance")+xlab("Ratio")+
  scale_y_continuous(labels = scales::percent, limits = c(.5,1))+
  geom_path(aes(x=ratio, y=pNoJND), color="blue", size=2, alpha = .7)+
  theme(aspect=1)+ggtitle("No JND Model")

# Intuitive JND Model
ggplot(exampleDat, aes(x = ratio, y = pIntJND))+
  theme_classic(base_size=15)+
  ylab("Performance")+xlab("Ratio")+
  scale_y_continuous(labels = scales::percent, limits = c(.5,1))+
  geom_path(aes(x=ratio, y=pIntJND), color="green", size= 2, alpha = .7)+
  theme(aspect=1)+ggtitle("Intuitive JND Model")

# Common JND Model
ggplot(exampleDat, aes(x = ratio, y = pComJND))+
  theme_classic(base_size=15)+
  ylab("Performance")+xlab("Ratio")+
  scale_y_continuous(labels = scales::percent, limits = c(.5,1))+
  geom_path(aes(x=ratio, y=pComJND), color="red", size= 2, alpha = .7)+
  theme(aspect=1)+ggtitle("Common JND Model")
```



##### Model fitting on sample data #####

```{r Load Example Data}
data <- read.csv("sample_data.csv")
```

```{r Group model fits}
# You can fit each subject separately with each model, or collapse across all subjects and fit them together.
# For this demo, we are fitting all subjects together.

# fitting with No JND Model
all.NoJND <- solnp(subjectParams.NoJND,NLL.NoJND,ineqfun=NULL,ineqLB=NULL,ineqUB=NULL,LB=lb.NoJND,UB=ub.NoJND,
                      control=NULL,trialParams=data$NumberRatio,outcomes=data$Accuracy)

# fitting with Intuitive JND Model
all.IntJND <- solnp(subjectParams.IntJND,NLL.IntJND,ineqfun=NULL,ineqLB=NULL,ineqUB=NULL,LB=lb.IntJND,UB=ub.IntJND,
                   control=NULL,trialParams=data$NumberRatio,outcomes=data$Accuracy)

# fitting with Common JND Model
all.ComJND <- solnp(subjectParams.ComJND,NLL.ComJND,ineqfun=NULL,ineqLB=NULL,ineqUB=NULL,LB=lb.ComJND,UB=ub.ComJND,
                   control=NULL,trialParams=data$NumberRatio,outcomes=data$Accuracy)


# measure of fit: Bayesian Information Criterion (lower values better)
# BIC  = 2 * NLL + (# model parameters) * log(# observations)
BIC.NoJND <- 2*tail(all.NoJND$values, n=1) + numParam.NoJND*log(nrow(data))
BIC.IntJND <- 2*tail(all.IntJND$values, n=1) + numParam.IntJND*log(nrow(data))
BIC.ComJND <- 2*tail(all.ComJND$values, n=1) + numParam.ComJND*log(nrow(data))

print("BIC Values")
print(paste("No JND Model:", BIC.NoJND))
print(paste("Intuitive JND Model:", BIC.IntJND))
print(paste("Common JND Model:", BIC.ComJND))

# model parameters:
print("Model Parameters")
all.NoJND$pars # w, g
all.IntJND$pars # w, g, jnd
all.ComJND$pars # alpha, beta, g
```

```{r Plot of group model fits}
# Calculate average performance per ratio across subjects
plotData <- data%>%
  group_by(NumberRatio)%>%
  summarise(meanResp = mean(Accuracy), seResp = std.error(Accuracy))

#generate data for lines
groupModels <- data.frame()
for (ratio in seq(1,1.5,.01)){
  pNoJND <- prob.NoJND(all.NoJND$pars[1], all.NoJND$pars[2], ratio)
  pIntJND <- prob.IntJND(all.IntJND$pars[1], all.IntJND$pars[2], all.IntJND$pars[3], ratio)
  pComJND <- prob.ComJND(all.ComJND$pars[1], all.ComJND$pars[2], all.ComJND$pars[3], ratio)
  groupModels <- rbind(groupModels, data.frame(ratio, pNoJND, pIntJND, pComJND))
}

# Plot
# blue line = No JND Model
# green dashed line = Intuitive JND Model (almost totally overlaps with blue)
# red dashed line = Common JND Model
ggplot(plotData, aes(x = NumberRatio, y = meanResp))+
  geom_path(data = groupModels, aes(x=ratio, y=pComJND), color="red", size=1.5,alpha = .4, linetype = 2)+
  geom_path(data = groupModels, aes(x=ratio, y=pIntJND), color="green", size=1.5,alpha = .8, linetype = 2)+
  geom_path(data = groupModels, aes(x=ratio, y=pNoJND), color="blue", size=1.5, alpha = .8)+
  geom_point(alpha = .5, size=7, aes(colour = factor(NumberRatio)))+ 
  theme_classic(base_size=20)+
  ylab("% Correct")+xlab("Ratio")+
  geom_linerange(aes(x=NumberRatio+.02,ymin = meanResp - seResp, ymax = meanResp+seResp, colour=factor(NumberRatio)),size=1)+
  geom_hline(yintercept=.5, linetype = 3, colour="gray", size=1)+
  scale_color_manual(values = rev(rainbow(7)))+
  scale_y_continuous(labels = scales::percent)+
  theme(legend.position = "none", aspect = .8)
```


